{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "playerbio.serviceAccountName" . }}
  labels:
{{ include "playerbio.labels" . | nindent 4 }}
{{- end -}}
